"""
Neo4j → Obsidian Writeback — When the brain discovers something,
create a new vault note so the human can see it.
"""
import os, re
from datetime import datetime
from neo4j import GraphDatabase
from pathlib import Path

VAULT = Path(r"C:\Users\x47th\OneDrive\Desktop\biiiiiiiiiiiiigggggggggg labbbbbbbbbbbbb\big lab")
NEO4J = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", os.getenv("NEO4J_PASSWORD", "UAID2026secure!")))

def discover_and_write():
    """Find Query nodes without corresponding vault notes, create them."""
    created = 0
    with NEO4J.session() as s:
        # Find recent queries not yet written to vault
        queries = s.run("""
            MATCH (q:Query)
            WHERE NOT EXISTS {
                MATCH (n:Note) WHERE n.name CONTAINS q.text OR q.text CONTAINS n.name
            }
            RETURN q.text as text, q.response as response, q.timestamp as ts
            ORDER BY q.timestamp DESC LIMIT 5
        """).data()

        for q in queries:
            title = q["text"][:80].replace("/", "-").replace("\\", "-").strip()
            note_path = VAULT / f"Query - {title}.md"
            if note_path.exists():
                continue

            content = f"""# Query: {q['text'][:100]}

> Auto-generated by Brain → Obsidian writeback
> {q.get('ts', datetime.now().isoformat())}

## AI Response

{q['response'][:2000]}

---
*This note was automatically created from a UAID GraphRAG query.*
"""
            note_path.write_text(content, encoding="utf-8")
            created += 1
            print(f"   📝 Created: {note_path.name}")

    return created


# ── CLI ────────────────────────────────────────────────
if __name__ == "__main__":
    n = discover_and_write()
    print(f"\n✅ {n} new vault notes created from Neo4j discoveries")
